-- ToDo adminに100件
INSERT INTO
    todos (
        todo,
        username,
        status,
        detail,
        created_at,
        updated_at
    )
VALUES
    (
        '買い物1',
        'admin',
        false,
        'スーパーで食材を購入する',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '図書館に行く2',
        'admin',
        false,
        '本を借りる',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '皇居ラン3',
        'admin',
        false,
        '皇居の周りを1周30分目安で走る！',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'コンビニに行く4',
        'admin',
        false,
        'ブラックサンダーを買う5',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'カレーを作る6',
        'admin',
        false,
        '食材を買うのを忘れずに・・・',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'パソコンを買う7',
        'admin',
        false,
        'メモリ32GBは欲しい',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ8',
        'admin',
        false,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ9',
        'admin',
        false,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ10',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ11',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ12',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ13',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ14',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ15',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ16',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ17',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ18',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ19',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ20',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '買い物1',
        'admin',
        false,
        'スーパーで食材を購入する',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '図書館に行く2',
        'admin',
        false,
        '本を借りる',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '皇居ラン3',
        'admin',
        false,
        '皇居の周りを1周30分目安で走る！',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'コンビニに行く4',
        'admin',
        false,
        'ブラックサンダーを買う5',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'カレーを作る6',
        'admin',
        false,
        '食材を買うのを忘れずに・・・',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'パソコンを買う7',
        'admin',
        false,
        'メモリ32GBは欲しい',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ8',
        'admin',
        false,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ9',
        'admin',
        false,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ10',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ11',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ12',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ13',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ14',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ15',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ16',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ17',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ18',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ19',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ20',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '買い物1',
        'admin',
        false,
        'スーパーで食材を購入する',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '図書館に行く2',
        'admin',
        false,
        '本を借りる',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '皇居ラン3',
        'admin',
        false,
        '皇居の周りを1周30分目安で走る！',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'コンビニに行く4',
        'admin',
        false,
        'ブラックサンダーを買う5',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'カレーを作る6',
        'admin',
        false,
        '食材を買うのを忘れずに・・・',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'パソコンを買う7',
        'admin',
        false,
        'メモリ32GBは欲しい',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ8',
        'admin',
        false,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ9',
        'admin',
        false,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ10',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ11',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ12',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ13',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ14',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ15',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ16',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ17',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ18',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ19',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ20',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '買い物1',
        'admin',
        false,
        'スーパーで食材を購入する',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '図書館に行く2',
        'admin',
        false,
        '本を借りる',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '皇居ラン3',
        'admin',
        false,
        '皇居の周りを1周30分目安で走る！',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'コンビニに行く4',
        'admin',
        false,
        'ブラックサンダーを買う5',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'カレーを作る6',
        'admin',
        false,
        '食材を買うのを忘れずに・・・',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'パソコンを買う7',
        'admin',
        false,
        'メモリ32GBは欲しい',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ8',
        'admin',
        false,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ9',
        'admin',
        false,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ10',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ11',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ12',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ13',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ14',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ15',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ16',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ17',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ18',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ19',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ20',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '買い物1',
        'admin',
        false,
        'スーパーで食材を購入する',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '図書館に行く2',
        'admin',
        false,
        '本を借りる',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '皇居ラン3',
        'admin',
        false,
        '皇居の周りを1周30分目安で走る！',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'コンビニに行く4',
        'admin',
        false,
        'ブラックサンダーを買う5',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'カレーを作る6',
        'admin',
        false,
        '食材を買うのを忘れずに・・・',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'パソコンを買う7',
        'admin',
        false,
        'メモリ32GBは欲しい',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ8',
        'admin',
        false,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ9',
        'admin',
        false,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ10',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ11',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ12',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ13',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ14',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ15',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ16',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ17',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ18',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ19',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '終わったやつ20',
        'false',
        true,
        '本当に終わった・・・？',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'ジムに行く',
        'user',
        false,
        '運動する',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        '空を飛ぶ',
        'user',
        true,
        '飛べたらいいなぁ',
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );

-- 認証テーブルへのダミーデータの追加
-- password：adminpass
INSERT INTO
    authentications (username, password, authority)
VALUES
    (
        'admin',
        '$2a$10$lNH4dLsCH4/g7aZZq14QG.PvnC7rkeN395ZWanW/hTOi5k6y009mm',
        'ADMIN'
    );

-- password：userpass
INSERT INTO
    authentications (username, password, authority)
VALUES
    (
        'user',
        '$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2',
        'USER'
    );

-- 以下MAXユーザー(上記＋48ユーザー)
INSERT INTO
    authentications (username, password, authority)
VALUES
    (
        'user1',
        '$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2',
        'USER'
    );

INSERT INTO
    authentications (username, password, authority)
VALUES
    (
        'user2',
        '$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2',
        'USER'
    );