spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/springdb
    username: springuser
    password: p@ss
  sql:
    init:
      #mode: never
      mode: always #アプリケーション起動時にSQLを流す

#logging:
#  level:
#    com.example.webapp.repository: DEBUG