INSERT INTO authentications (username, password, authority)VALUES('admin','$2a$10$lNH4dLsCH4/g7aZZq14QG.PvnC7rkeN395ZWanW/hTOi5k6y009mm','ADMIN');
-- password：userpass
INSERT INTO authentications (username, password, authority) VALUES('user1','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user2','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user3','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user4','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user5','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user6','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user7','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user8','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user9','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user10','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user11','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user12','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user13','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user14','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user15','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user16','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user17','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user18','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user19','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user20','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user21','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user22','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user23','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user24','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user25','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user26','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user27','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user28','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user29','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user30','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user31','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user32','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user33','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user34','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user35','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user36','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user37','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user38','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user39','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user40','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user41','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user42','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user43','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user44','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user45','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user46','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user47','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user48','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');
INSERT INTO authentications (username, password, authority) VALUES('user49','$2a$10$/jar9xXQ6lrnVjLvLGv5BepFkLnGIO49RrGx42p2i.1hQt1BZ/7E2','USER');

INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO1','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO2','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO3','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO4','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO5','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO6','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO7','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO8','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO9','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO10','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO11','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO12','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO13','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO14','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO15','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO16','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO17','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO18','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO19','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO20','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO21','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO22','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO23','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO24','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO25','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO26','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO27','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO28','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO29','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO30','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO31','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO32','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO33','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO34','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO35','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO36','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO37','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO38','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO39','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO40','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO41','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO42','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO43','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO44','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO45','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO46','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO47','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO48','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO49','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
INSERT INTO todos (todo,username,status,detail,created_at,updated_at)VALUES('ToDO50','admin',false,'テストToDo',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP);
